### PR TITLE
Update display of products and tools pages.

### PR DESCRIPTION
**Pull request by dj2**
This CL updates the products and tools pages to use a more card centric
design.

### CODE REVIEW

**Comment by dj2** [comment]
Looks like I broke some tests since I shuffled things around in the page. Will take a look tomorrow if I have time to see if I can fix them easily.

**Comment by lynnchalati** [comment]
Hey! I could be wrong, but if the checks pass, there will be a button that says "view deployment". The mockups Nick did are great, but we're going to be making changes to them so they're not our finalized mockups. This is pretty cool though; thanks for putting in the time!

**Comment by obrien-j** [comment]
IANAD(esigner), but would it be cleaner to have the cards aligned vertically... seems a bit odd with 2 columns and the cards only aligning at the tops.

**Comment by dj2** [comment]
I haven't been able to get them to align height wise yet. Wanted to see what folks thought in general before trying to sink time into aligning vertically.

**Comment by khalidelaggan** [comment]
Thank you so much @dj2 for jumping into this redesign enhancements, @victoriachanimal and I will be more than happy to assist you with anything needed.

Where can I find the link for the mocks that @nmakuch created?

Also, I would love to take the opportunity and add this awesome work into our website portage, so we can share any feedback/demo with the rest of the team.

**Comment by khalidelaggan** [comment]
Also the website will be undergoing another round of CSS refactoring soon, and it will be an excellent opportunity to align your work to this new pipeline.

**Comment by lynnchalati** [comment]
The original mockups that Nick did are here: https://trello.com/c/6D54eQ7n/14-product-page-redesign

I noted the information that Dan's working on here: https://trello.com/c/FmZMRvMs/15-product-page-mockups

Michelle and Dan are working together on this with Vic's help too :)

**Pull request merged**
