### PR TITLE
Update/privacy policy content update

### PR DESCRIPTION
**Pull request by omartehsin1**
# Summary | Résumé

Privacy notice content update

[EN](https://docs.google.com/document/d/1uN1JWDOe_G6Y9XJvfmZsWY2lFr9dK8cd/edit#)

[FR](https://docs.google.com/document/d/1EXzJWZS5Y1zqb5CmGC6vOg-TKd9x1fZdP4_jYzdCntQ/edit#)

### CODE REVIEW

**Comment by Charcharbinkz** [comment]
Thanks!! Looks great! I'm going to pass along the PR to Sean Boots.

Something I should have mentioned earlier: Before, we had one main privacy notice in the footer and then two specific task-based ones.

The two others:
- Newsletter subscribe box (https://digital.canada.ca/#privacy-notice-modal)
- Bottom of individual job postings (https://digital.canada.ca/legal/privacy-notice/)

We've combined all three into this one notice. So where we previously linked to those other two smaller ones, we can now direct to this single source of truth (https://digital.canada.ca/legal/privacy/)

**Comment by sboots** [comment]
So stoked that this is happening! 🎉  Amazing work @omartehsin1 and @Charcharbinkz ! Thanks for updating the links for the newsletter signup and job postings privacy links likewise!

~Two~ er, several quick things,
- In `layouts/partials/mailing-list.html`, the same template partial is used in English and in French, but at the moment the link will only go to the EN version of the privacy page. It might be easiest to add an entry in the i18n files for the privacy page URL, something like `/legal/privacy/` in EN and `/transparence/confidentialite/` in FR? (Right now it's a 404 on the French version of the careers page, where the newsletter partial is visible.)
- In `layouts/section/job-posting.fr.html`, I think it should link to `/transparence/confidentialite/` (the updated privacy page) instead of `/transparence/avis-de-securite/` (the security notice page?)

These are less critical but:
- If our system supports redirects, once this is in place, could we automatically redirect people from `/legal/privacy-notice/` (the old recruitment privacy notice) to `/legal/privacy/`? (And ditto for `/transparence/enonce-de-confidentialite/` to `/transparence/confidentialite/` in FR?) Just in case anyone has linked to these from somewhere outside our site / on old parts of the website we've missed updating etc.
- Once that's done it'd be great to actually delete the old recruitment privacy pages (`content/en/legal/privacy-notice.html` and `content/fr/legal/privacy-notice.html`) which are no longer used
- And we could also remove the `<section id="privacy-notice-modal">…` part at the bottom of `layouts/partials/mailing-list.html` since it won't be needed anymore. 

Sorry for all the comments. 😂 The content and formatting on the new pages all looks spot-on! Thanks so much for doing this!

**Comment by omartehsin1** [comment]
hey @sboots, thanks for your comments, made the changes. For redirects, I've left up the privacy-notice.html page up, since that will handle the redirect but the content has changed. I did something similar for tools and resources (which redirects to guides), for some reason it is not working on localhost, but is working on the live site. So we might have a similar issue with privacy-notice, I'll keep an eye out but the redirects _should_ work

**Review by Charcharbinkz — APPROVED** [review]

**Comment by sboots** [comment]
Super nice work – thanks for all these updates @omartehsin1 ! 🙌

**Pull request merged**
