### PR TITLE
Add missing page titles.

### LINKED ISSUE #2420: Bug: Missing Page titles and h1's
This is to satisfy WCAG [Success Criterion 2.4.2 (Level A)](https://www.w3.org/TR/WCAG21/#page-titled) and [Success Criterion 2.4.6  (Level AA)](https://www.w3.org/TR/WCAG21/#headings-and-labels)

The following pages don't have titles.

- [ ] https://digital.canada.ca/meet-the-team/
- [ ] https://numerique.canada.ca/rencontrez-lequipe/
- [ ] https://digital.canada.ca/our-values/
- [ ] https://numerique.canada.ca/nos-valeurs/

### PR DESCRIPTION
**Pull request by dj2**
# Summary | Résumé

This PR adds the missing titles from the Our Values and Meet the Team
pages.

Fixes #2420

### CODE REVIEW

**Comment by dj2** [comment]
Converting this to draft, just realized this adds an `h1` to the page as well, which fixes the `h1` issue but doesn't fit the rest of the page.

**Review by CalvinRodo — DISMISSED** [review]
:taco::cat:

**Comment by amazingphilippe** [comment]
If we can hold up before merging. This doesn't align with the new designs. The rationale for removing the title from the menu is that it help distinguish it as the page heading. Otherwise, it blends too much with the header and we lose the connection with the main content.

**Comment by dj2** [comment]
I think we need to figure out how to align the new design with the old framework. We may need to change these pages slightly to fit the existing site until we're ready to cut all of the base templates over to the new design otherwise we're going to have accessibility issues.

**Comment by amazingphilippe** [comment]
This PR itself creates an accessibility issue. Not one that can trigger automated tools, but still causes accessibility issues. The [Info and relationship](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) criterion isn't fixed with this PR. WCAG guidelines suggests that grouping related elements with a single background colour is one way to ensure that the relationship between the heading 1 and the rest of the content is preserved. So yes, we are fixing the issue for users using screen readers, but not for users relying on their vision to parse content. 

So if lets just make sure we  have another issue open for exactly that since we aren't fixing the entire issue here. 

Alternatively, without too much radical change, we could find a way to change the background colour under the h1 to match the body text.

**Comment by amazingphilippe** [comment]
Something like this could be very simple if you're okay with it
1. Removed `color: #fff;` from h1
2. The different banner containers we have take `background-color: #f9f9f9;` and we remove `color: #fff;` if they have it. 

Capture d’écran, le 2021-07-21 à 11 40 31

Just need to test with our different page types

**Comment by dj2** [comment]
Yea, that's what I've done locally, just trying to figure out how to apply the CSS to the french meet-the-team page as the selector has an encoded character in it.

**Comment by victoriachanimal** [comment]
Thanks all (and for flagging @amazingphilippe). 

Captured these issues in #2422  — please feel free to add to it and am hoping the temporary fix works, but agree to hold off on merging and hoping this temporary fix can work. 

Also looping in @omartehsin1 for line of sight as we're building two other Talent-related pages which feature the redesigned header on white background. 

Would love to chat about this next week when @katedee is back to discuss a path forward with future redesigns.

**Comment by dj2** [comment]
Ok, I got it working changing just those pages, but then it looked bad when clicking through the menu as it would jump back and forth, so I changed  the top level pages to be consistent. (Note, this doesn't change individual blog articles, as they use a different template and I wasn't sure what we'd wan to do with the header there).

**Comment by amazingphilippe** [comment]
I think this is the right approach for the moment. We can tweak it later as we tackle the base layout. Some pages are currently very misaligned!

Screenshot 2021-07-21 at 13-37-50 Meet the Team - Canadian Digital Service

**Comment by dj2** [comment]
Yea, the meet the team page seems to be wider then the other pages.

**Comment by dj2** [comment]
So, thoughts? Is this mergable as is and we can apply other fixes later or do we want to change something before merging?

**Comment by amazingphilippe** [comment]
I'm not sure what happened, but the blog header image doesn't center and cover anymore. Was there anything that changed for these in previous commits?

Current website:
Screenshot 2021-07-22 at 14-14-50 A faster way to create privacy and consent notices in government - Canadian Digital Service

This PR:
Screenshot 2021-07-22 at 14-14-59 A faster way to create privacy and consent notices in government - Canadian Digital Service

**Comment by dj2** [comment]
Good catch. Should be fixed with new deploy.

**Review by amazingphilippe — APPROVED** [review]
Looks good to me!

**Review by victoriachanimal — APPROVED** [review]

**Pull request merged**
