### PR TITLE
Add Our Values page.

### PR DESCRIPTION
**Pull request by dj2**
# Summary | Résumé

This PR adds an our-values page. It is not linked from anywhere at this
point. The gray boxes in the mockup are missing, but the subscribe link
is provided for the newsletter.

Issue #2123

### CODE REVIEW

**Comment by dj2** [comment]
I started building this page out. This PR is currently a draft. What do ya'll think? (The French page probably has spelling mistages as I transcribed from Figma as it wouldn't let me copy ....)

**Comment by dj2** [comment]
https://digital-cana-values-hwt4nefb2e.herokuapp.com/our-values/

**Review by victoriachanimal — APPROVED** [review]

**Comment by dj2** [comment]
Thanks to @victoriachanimal I managed to get the content for the French page, so the real content is in both pages. I've taken this out of draft so should be good to go, I think.

**Review by brdunfield — APPROVED** [review]
LGTM! Are there any plans to link to this page from elsewhere on the site?

**Comment by dj2** [comment]
It's in the new menu bar, but figured we could start building it out before linking. There are still the grey boxes on the bottom to add at some point. This at least gets the basis in place we can iterate on.

**Pull request merged**
