### PR TITLE
Update styles of our team section.

### PR DESCRIPTION
**Pull request by dj2**
This CL updates the styles on the our team section of the homepage.

### CODE REVIEW

**Comment by victoriachanimal** [comment]
Nice @dj2!! Could we add a small margin-bottom style to an existing mobile_only rule?

@media (max-width: 767px)
.homepage--our-team .btn {
    text-align: left;
    **margin-bottom: 10px;**
}

**Comment by dj2** [comment]
Done.

**Comment by victoriachanimal** [comment]
Looks amazing! @khalidelaggan is this section good for accessibility? Just a note that for the branch conflicts, I believe we just have to take this part out before merging:

**<<<<<<< 05_single_our_team
.accueil .homepage--our-team,
.home .homepage--our-team,
=======
.accueil .newsletter-subscribe h2,
.home .newsletter-subscribe h2,
>>>>>>> master**

**Comment by khalidelaggan** [comment]
Looks great, no issues reported so far.

**Pull request merged**
