### PR TITLE
Enable sitemap generation

### PR DESCRIPTION
**Pull request by dj2**
Turn on sitemap generation in the Hugo configuration

### CODE REVIEW

**Comment by dj2** [comment]
Thoughts?

**Comment by khalidelaggan** [comment]
Doing the Diff now for the newly generated file

https://digital-canada-ca-pr-1031.herokuapp.com/sitemap.xml
vs 
https://digital.canada.ca/sitemap.xml

**Comment by dj2** [comment]
Interesting, was the previous one done by hand? It didn't show up in my dev instance?

**Comment by khalidelaggan** [comment]
It looks great! @dj2 , however we will need to create a sitemap index for our bilingual site

**Comment by dj2** [comment]
There should be a sitemap for the french site already?

**Comment by khalidelaggan** [comment]
Got it, for some reason it wasn't loading few minutes ago :)

**Comment by khalidelaggan** [comment]
@lynnchalati we will have to create a few sub-tasks to make use of the generated sitemap data en/fr into our site frontend to make the site map accessible and available to users.

Details can be found here
https://www.w3.org/WAI/GL/WCAG20/WD-WCAG20-TECHS-20071218/G63.html

Happy to help with listing all the work needed in more details in Trello

**Comment by khalidelaggan** [comment]
Other than that, it looks great @dj2  thank you for this :)

**Pull request merged**
