### PR TITLE
Replacing "Who we are" with "Careers"

### PR DESCRIPTION
**Pull request by omartehsin1**
# Summary | Résumé

This branch takes care of bug #2464. "Who we are" originally took you to the "Meet the team" page. This changes the path, it will now take you to "Careers" which is the old "Join Our Team" page. The reason there are so many file changes is simply because of renaming. I changed "join-our-team" to "careers" in the layout and content folder. 

I also had to manually change some of the md files links that previously had 'join-our-team', since the url has changed as well and some of the tests were failing.

### CODE REVIEW

**Comment by omartehsin1** [comment]
@CalvinRodo @dj2 , do either one of you know whether renaming the "join-our-team" folder to "careers" has any issues with strapi? I haven't seen anything that can cause any issues but just want to verify

**Comment by CalvinRodo** [comment]
> @CalvinRodo @dj2 , do either one of you know whether renaming the "join-our-team" folder to "careers" has any issues with strapi? I haven't seen anything that can cause any issues but just want to verify

Unfortunately I'm not terribly knowledgable about strapi or I should more accurately say I've never used it or looked at it before.

**Comment by dj2** [comment]
I don't know. You can create job postings from strapi, how do those work, where do they go? @victoriachanimal may have more context.

**Comment by victoriachanimal** [comment]
@omartehsin1 Not sure if this is helpful, but Bethany worked on some info about the CMS architecture here: https://github.com/cds-snc/cds-website-terraform

**Comment by omartehsin1** [comment]
Ok, so changes do need to be made for the PR Bot


Screen Shot 2021-08-13 at 12 52 59 PM


I changed this do 'careers'. This should be ready to review.

**Comment by victoriachanimal** [comment]
Woot thanks so much @omartehsin1 ! 

Noticed a small typo here for "partnerships" : 
Screen Shot 2021-08-13 at 12 57 01 PM

^ other than that, I defer to Dan, Calvin and/or Kate for reviews / the green light!

**Review by dj2 — APPROVED** [review]
Code LGTM.

**Pull request merged**
