### PR TITLE
Added a11y Github action

### PR DESCRIPTION
**Pull request by khalidelaggan**

### CODE REVIEW

**Comment by khalidelaggan** [comment]
This has been just a trial to see how GH action works and so far it seems to work just fine :)
https://github.com/cds-snc/digital-canada-ca/commit/166cf1d2efe2526cc48b80b987addab7027a7758/checks

It took me a serious of events/commits to understand the workflow part, but for now I will work on fixing all the issues reported back.

**Comment by brdunfield** [comment]
Looking good! Once the action has been modified to more reliably run more URLs, are you planning to add other website pages (maybe job postings, errors, any contact pages etc.)?

**Comment by khalidelaggan** [comment]
Absolutely, I will certainly add these pages as well to the list.

**Comment by khalidelaggan** [comment]
@brdunfield can we please get your approval or 👍  for this so we can ship it? :) 

Thank you so much for your help

**Comment by timarney** [comment]
That's a solid bump in the right direction.  Should be better on the real server.

Screen Shot 2019-10-02 at 2 37 23 PM

**Comment by khalidelaggan** [comment]
That's great!! we should also see a little increase in performance after our purge CSS exercise is completed :)

**Pull request merged**
