### PR TITLE
Take down Senior/Principal Dev Job Posting

### PR DESCRIPTION
**Pull request by jeffmaher**
Close the position to new applicants.

### CODE REVIEW

**Comment by jeffmaher** [comment]
Screenshot from review deployment, show the position no longer in the list.

Screen Shot 2020-09-04 at 16 42 34

**Comment by gilbrookiegirl** [comment]
Reviewed and confirmed.

**Review by gilbrookiegirl — DISMISSED** [review]

**Review by maxneuvians — APPROVED** [review]
LGTM

**Review by maxneuvians — APPROVED** [review]
🚀

**Pull request merged**
