### PR TITLE
Change heading structure for partnership list.

### PR DESCRIPTION
**Pull request by dj2**
# Summary | Résumé

This PR changes the partnership include to not use h1/h2 anymore.
Instead div's are used which are styled with classes `.h1` and `.h2`.
The top level div is marked as a `role=heading` but the others are not
as they don't really work like headings in the card.

Issue #2288

### CODE REVIEW

**Comment by dj2** [comment]
Thoughts? Removing the h1/h2 removes the level confusion. Seems to be a valid way to do it given https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA12 I think?

**Comment by brdunfield** [comment]
Looks like these styles are not applying to the tools and resources page.

In terms of overall method - I think this works until we can rework the site. Hopefully, eventually we can work the site to where it isn't necessary, and we can use proper html headings and hierarchies!

**Comment by dj2** [comment]
Fixed Tools-And-Resources. I ... may ... have forgotten to change the tags over there, heh.

**Comment by dj2** [comment]
Discussed with @brdunfield and they suggested a much better potential way of doing this by providing the level to the partial and fully decoupling the style from the markup. Moved this to draft so I can try to get that working.

**Comment by dj2** [comment]
I liked into passing the level as a param. The issue is, these are using `.Render` as they're layouts, not partials. As far as I can tell, you can't pass params to the `.Render` method. I tried playing with `.Scratch` but I never managed to get a value passed through. So, I don't see a nicer way to do this at the moment.

**Comment by brdunfield** [comment]
That's a shame. Well in that case, again, I don't think heading level 1 and 2 is appropriate for these cards. I know that skipping heading levels is not best practice, but can we just set these to be the lowest heading levels that would appear in our various combinations? I think skipping a heading level on one page is better than having heading levels that don't make sense in the context of the page.

**Comment by dj2** [comment]
In the case of this PR, I'm removing the `h1`, `h2` labels and using a `div` that styles with a class. In the case of these cards, does using a heading even make sense? At least the `h2`s seem very weird to me as headings.

**Pull request closed without merging**
