### PR TITLE
Platform tools page

### PR DESCRIPTION
**Pull request by timarney**
Create a new page that lists our dev tools on digital.canada.ca

Hey @lynnchalati 

The platform team has been discussing the need for a landing page to help direct people to the tools we've been building.

As we've been giving presentations to Gov Depts they often as "Where can I find X" to which we reply "It's all on Github".  Problem being the the tools are buried amongst all our other repos.

This is a first crack to kick-start getting that page built out + start the discussion 

And hey it make a nice demo for STT ;)

https://digital-canada-ca-pr-653.herokuapp.com/platform

### CODE REVIEW

**Comment by obrien-j** [comment]
1: No pushes before OL.

2: I'd suggest putting in a platform@ email address as well, not to steal your thunder Bryan, but given the fluidity of the team, it'd be best to operate on a 'group' question-interest model.

3: other thoughts offline when I get a chance.

**Comment by willeybryan** [comment]
Yeah since no one replied I worked with outreach to Proof it and they are getting it translated right now for us (I assume OL means Official Languages).

Not my Thunder to steal, Platform email address is fine I will talk to Vic about it. 

> 1: No pushes before OL.
> 
> 2: I'd suggest putting in a platform@ email address as well, not to steal your thunder Bryan, but given the fluidity of the team, it'd be best to operate on a 'group' question-interest model.
> 
> 3: other thoughts offline when I get a chance.

**Comment by timarney** [comment]
@willeybryan the preview deploy should have all your updates (as you make commits to this PR)

https://digital-canada-ca-pr-653.herokuapp.com/platform

**Comment by willeybryan** [comment]
That is did, the first time I made changes it just took like 30 minutes so I was worried it wouldn't. Got it all sorted now. We are even updating the Platform@cds-snc.ca email so it doesn't go to just Dave and Mario.

**Pull request closed without merging**
