### PR TITLE
Update contact us styles.

### PR DESCRIPTION
**Pull request by dj2**
This CL updates the 'contact us' section to the new styles.

### CODE REVIEW

**Comment by khalidelaggan** [comment]
@dj2 flagging few conflicts in this branch

**Comment by dj2** [comment]
All of these branches will probably have conflicts. I'll resolve them as I merge in various bits ....

**Comment by victoriachanimal** [comment]
Ohhh! Looks good to me! Only thing is, we might want to make the h4 font-size ("Join the conversation" ie. .social-links-footer h4) a little bigger - it's currently at 1.1rem, but we might want to change it to 2.3rem (closer to 24px) - would it be easier for me to merge this PR and then make a new small PR addressing this? @dj2 @khalidelaggan

**Comment by dj2** [comment]
Font size should be fixed now

**Comment by victoriachanimal** [comment]
@khalidelaggan are we good with accessibility on this one?

**Pull request merged**
