### PR TITLE
Content update and redesign

### PR DESCRIPTION
**Pull request by omartehsin1**
# Summary | Résumé

https://www.figma.com/file/tkkBvItXhLQB6jDokbRfyp/the-REAL-CDS-Website-Revamp?node-id=2120%3A17176

Redesign of several pages:
- Changed "Partnerships" to "Coaching and Advice"
- Split "Tools and Resources" to "Product Suite" and "Guides"
- Updated content on the homepage and added a new card
- Updated Menu, added a dropdown

### CODE REVIEW

**Comment by victoriachanimal** [comment]
Yay! Thanks for your work on this @omartehsin1! Pages look great to me, also tested links. 

Will defer to @Charcharbinkz and @katedee on the below:

[Product Suite page](https://digital-cana-redesign-h-aoeu3y.herokuapp.com/product-suite/):  
- Under "Product Suite" h1 banner, confirming if the tagline is "Building government solutions so you don't have to." or "Integrate our ready-to-use tools into your existing systems."

Screen Shot 2022-02-08 at 9 51 34 AM

- Under "All of our products are heading," just double-checking if the checkmark points are in green or black. 
Screen Shot 2022-02-08 at 9 46 25 AM

Thanks all!

**Comment by Charcharbinkz** [comment]
This is AMAZING!!! I am so excited!

Agree with the two points above from @victoriachanimal @katedee 

Other Qs:

### **Nav bar**

- [ ] Sentence case for "Coaching and **a**dvice"
- [ ] I found myself trying to click "How we can help" text in nav bar. But we of course don't have a page to link it to. Is it possible to have this text link to the section on the homepage where this info begins? cc @katedee in case this is bad practice
image

### **Homepage**

- [ ] Sentence case for "Coaching and **a**dvice" header
- [ ] Alt text for coaching and advice image - wondering if it carried over from our previous redesign? I can't seem to see it pop up.
- [ ] For accessibility, should the subheadings in each of the 3 sections be an H4? The parts that start with, "If you need..." cc @katedee for views on this as well!
- [ ] For the Guides blurb, as I'm re-reading it, it's now feeling clunkier than the other two. Can remove the last part of the sentence. (Highlighted words that can be removed. I also updated this in Figma)
image
image

### **Product suite**

- [ ] Sentence case for title: "Product **s**uite"
- [ ] Agree with @victoriachanimal 's point above about the tagline update.
- [ ] "All of our products are" - wondering if this should be H2 for accessibility? cc @katedee for views as well. 
- [ ] Change "All of our products are:" to "Our products are:" (Just learned the pilots are not yet all of those things). French is "Nos produits sont :" -- updated in Figma as well. 

- [ ] GC Notify card: button text looks to be bleeding out in French when screen size shrinks. Let me know if this is something that should be fixed by content.
image

- [ ] The product cards have the first sentence from Figma displayed, but they each have 1-2 more sentences that don't look to be captured.
Screen Shot 2022-02-08 at 11 41 55 AM


### **Guides**

- [ ] Sentence case for "Learn **m**ore" button text
image

- [ ] Book gov appointment card missing colon in English & French after "Documentation"
Screen Shot 2022-02-08 at 11 45 00 AM
Screen Shot 2022-02-08 at 11 45 43 AM

**Comment by omartehsin1** [comment]
@Charcharbinkz regarding " GC Notify card: button text", is there any way to condense the button test? there's not a lot of room in the card, would something like Visit GC Notify work?

**Comment by Charcharbinkz** [comment]
@omartehsin1 For sure. I think the button text could even be "GC Notify website" and then we can add the full "Visit GC Notify Website" as the accessible button text?

Which is making me just notice that the accessible button text for GC Forms may be attached to the GC Notify button right now. My bad for the confusing placement of that in Figma.

**Review by Charcharbinkz — APPROVED** [review]

**Pull request merged**
